### ISSUE TITLE
Team data / entity processed out of order crash

### ISSUE THREAD

**Issue by timkurvers** [timkurvers/redota#54]
In match [2569470828](https://timkurvers.github.io/redota/#/matches/2569470828) the radiant data entity (`CDOTA_DataRadiant`) is processed before the radiant team entity (`CDOTATeam`) which crashes ReDota:

```
TypeError: team is undefined
    at processTeamData@http://localhost:8080/redota-parser+viewer-2061e105.js:4467:21
    at onEntities@http://localhost:8080/redota-parser+viewer-2061e105.js:4145:21
    at emit@http://localhost:8080/redota-vendor-cff3a606.js?656609026929b1d1db9f:12120:17
    at onCSVCMsg_PacketEntities@http://localhost:8080/redota-parser+viewer-2061e105.js:2563:18
```

**Comment by timkurvers** [comment]
Fixed in 34b926766a5a6479ac5ee5afc6849c3de3ffd6e0.
