### ISSUE TITLE
Replays after spring cleaning patch fail to parse

### ISSUE THREAD

**Issue by timkurvers** [timkurvers/redota#66]
Sample match: https://timkurvers.github.io/redota/#/matches/find/6492737816

```
Error: unable to find existing entity: 153
    at onCSVCMsg_PacketEntities@https://timkurvers.github.io/redota/redota-parser+viewer-0cd1b6d8.js:1:201430
    at 7187/i.prototype.emit@https://timkurvers.github.io/redota/redota-vendor-6c7c4893.js?ae3229f77947a58bf8f5:2:148540
    at onCDemoPacket@https://timkurvers.github.io/redota/redota-parser+viewer-0cd1b6d8.js:1:197645
    at 7187/i.prototype.emit@https://timkurvers.github.io/redota/redota-vendor-6c7c4893.js?ae3229f77947a58bf8f5:2:148540
    at seek@https://timkurvers.github.io/redota/redota-parser+viewer-0cd1b6d8.js:1:197155
    at step@https://timkurvers.github.io/redota/redota-parser+viewer-0cd1b6d8.js:1:196671
    at start@https://timkurvers.github.io/redota/redota-parser+viewer-0cd1b6d8.js:1:196649
```

**Comment by timkurvers** [comment]
Fixed in 92a94da1866145ae12c19c9e117230268f57db2d. New build is available on website.
